trigger:
  branches:
    include: [ main ]

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    curl -fsSL https://releases.hashicorp.com/terraform/1.9.8/terraform_1.9.8_linux_amd64.zip -o terraform.zip
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/
    terraform -version
  displayName: 'Install Terraform'

- task: AzureCLI@2
  displayName: 'Terraform init & plan'
  inputs:
    azureSubscription: 'sc-practice'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform init
      terraform plan