trigger:
  branches:
    include: [ main ]

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'Terraform init & plan'
  inputs:
    azureSubscription: 'sc-practice'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      terraform init
      terraform plan